//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.27 at 03:56:12 PM CET 
//


package com.unalsoft.elitefle.entity.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the elite-fle.text package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: elite-fle.text
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Element }
     * 
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link Referent }
     * 
     */
    public Referent createReferent() {
        return new Referent();
    }

    /**
     * Create an instance of {@link Ellipse }
     * 
     */
    public Ellipse createEllipse() {
        return new Ellipse();
    }

    /**
     * Create an instance of {@link Coreferent }
     * 
     */
    public Coreferent createCoreferent() {
        return new Coreferent();
    }

    /**
     * Create an instance of {@link Prop }
     * 
     */
    public Prop createProp() {
        return new Prop();
    }

    /**
     * Create an instance of {@link DocumentTexte }
     * 
     */
    public DocumentTexte createDocumentTexte() {
        return new DocumentTexte();
    }

    /**
     * Create an instance of {@link Entete }
     * 
     */
    public Entete createEntete() {
        return new Entete();
    }

    /**
     * Create an instance of {@link Contenu }
     * 
     */
    public Contenu createContenu() {
        return new Contenu();
    }

    /**
     * Create an instance of {@link Titre }
     * 
     */
    public Titre createTitre() {
        return new Titre();
    }

    /**
     * Create an instance of {@link Phrase }
     * 
     */
    public Phrase createPhrase() {
        return new Phrase();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link SousTitre }
     * 
     */
    public SousTitre createSousTitre() {
        return new SousTitre();
    }

    /**
     * Create an instance of {@link Paragraphe }
     * 
     */
    public Paragraphe createParagraphe() {
        return new Paragraphe();
    }

    /**
     * Create an instance of {@link Activite }
     * 
     */
    public Activite createActivite() {
        return new Activite();
    }

}
