//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.27 at 03:56:12 PM CET 
//


package com.unalsoft.elitefle.entity.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "phraseOrElement"
})
@XmlRootElement(name = "paragraphe")
public class Paragraphe {

    @XmlElements({
        @XmlElement(name = "phrase", type = Phrase.class),
        @XmlElement(name = "element", type = Element.class)
    })
    protected List<Object> phraseOrElement;

    /**
     * Gets the value of the phraseOrElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phraseOrElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhraseOrElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Phrase }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getPhraseOrElement() {
        if (phraseOrElement == null) {
            phraseOrElement = new ArrayList<Object>();
        }
        return this.phraseOrElement;
    }

}
